[package]
name = "pkcs7"
version = "0.2.0"
authors = ["Jeff Carpenter <gcarpenterv@gmail.com>"]
description = "PKCS #7 padding"
repository = "https://github.com/jeffcarp/pkcs7"
license = "MIT"

[dependencies]
